/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Assignment;
import Business.Business;
import Business.Course;
import Business.CourseList;
import Business.Person.PersonDirectory;
import Business.Profiles.FacultyProfile;
import ManagerBean.CourseManagerBean;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author kunal
 */
public class FacultyAssignmentInfoJPanel extends javax.swing.JPanel {
    
    Business business;
   
    FacultyProfile faculty;
    javax.swing.JPanel CardSequencePanel;
    CourseList courselist;
    CourseManagerBean courseManagerBean;
    String selectedCourse=null;


    /**
     * Creates new form FacultyAssignmentInfoJPanel
     */
    public FacultyAssignmentInfoJPanel() {
        initComponents();
    }

    FacultyAssignmentInfoJPanel(Business business, FacultyProfile faculty, CourseManagerBean courseManagerBean, String selectedCourse, JPanel CardSequencePanel) {
        business = business;
        this.CardSequencePanel = CardSequencePanel;
        this.faculty = faculty;
        this.courselist = courselist;
        this.courseManagerBean = courseManagerBean;
        this.selectedCourse = selectedCourse;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAssignmentName = new javax.swing.JTextField();
        txtAssignmentMarks = new javax.swing.JTextField();
        txtAssignmentSubmissionDate = new javax.swing.JTextField();

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Assignment Information");

        jLabel1.setText("Assignment Name :");

        jButton1.setText("Create Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Assignment marks");

        jLabel3.setText("Assignment Submission Due date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(344, 344, 344))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAssignmentName, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(txtAssignmentMarks)
                    .addComponent(txtAssignmentSubmissionDate))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAssignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAssignmentMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAssignmentSubmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(0, 283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String assignmentName = txtAssignmentName.getText();
        String assignmentMarks =  txtAssignmentMarks.getText();
        String assignmentDate = txtAssignmentSubmissionDate.getText();
        
        Course course = courseManagerBean.findCourse(selectedCourse);
        
         Assignment assignment = new Assignment();
         assignment.setAssignmentId(0);
         assignment.setAssignmentName(assignmentName);
         assignment.setMarks(Integer.parseInt(assignmentMarks));
         assignment.setSubmissionDate(new Date(assignmentDate));
         
          course.addAssignment(assignment);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAssignmentMarks;
    private javax.swing.JTextField txtAssignmentName;
    private javax.swing.JTextField txtAssignmentSubmissionDate;
    // End of variables declaration//GEN-END:variables
}
